name: main

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t giuscri/csv2json .
        echo $DOCKER_PASSWORD | docker login -u giuscri --password-stdin
        docker push giuscri/csv2json:latest
